# AE 2 - Network 2

To save you some work, here are the three suggested matrices from the exercise:

In [31]:
import numpy as np
M1 = np.array([[0,1/3,0,1/2,0],[1/3,0,0,0,0],[0,1/3,0,0,1],[1/3,0,0,0,0],[1/3,1/3,0,1/2,0]])
print(M1)

[[0.         0.33333333 0.         0.5        0.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.         0.33333333 0.         0.         1.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.5        0.        ]]


In [32]:
M2 = M1.copy()
M2[:,2]=np.array([0,0,1,0,0])
print(M2)

[[0.         0.33333333 0.         0.5        0.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.         0.33333333 1.         0.         1.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.         0.5        0.        ]]


In [33]:
M3 = M1.copy()
M3[:,2]=np.array([0.2,0.2,0.2,0.2,0.2])
print(M3)

[[0.         0.33333333 0.2        0.5        0.        ]
 [0.33333333 0.         0.2        0.         0.        ]
 [0.         0.33333333 0.2        0.         1.        ]
 [0.33333333 0.         0.2        0.         0.        ]
 [0.33333333 0.33333333 0.2        0.5        0.        ]]


If you want to experiment with some random surfers, you can start with some initial population, e.g.

In [34]:
p = np.array([[100],[100],[100],[100],[100]])

 and try repeating the formulas below.
 **I recommend resetting `p` above between experiments, or it might get confusing.**

In [22]:
# Experiment with 

p = np.matmul(M1,p)
print(np.round(p,2))

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [46]:
# Experiment with M2
p = np.matmul(M2,p)
print(np.round(p,2))


[[5.0000e-02]
 [5.0000e-02]
 [4.9977e+02]
 [5.0000e-02]
 [9.0000e-02]]


In [72]:
# Experiment with M3
p = np.matmul(M3,p)
print(p)

[[ 86.84218224]
 [ 63.15785162]
 [171.05261388]
 [ 63.15785162]
 [115.78950064]]


Alternatively you might want to calculate the eigenvalues and eigenvectors.

In [57]:
l1, P1= np.linalg.eig(M1)
l2, P2= np.linalg.eig(M2)
l3, P3= np.linalg.eig(M3)

In [58]:
print(np.round(l1,2))

[ 0.    0.    0.53 -0.53  0.  ]


In [59]:
print(np.round(l2,2))

[ 1.    0.    0.53 -0.53  0.  ]


In [60]:
print(np.round(P2,2))

[[ 0.    0.    0.23  0.72  0.  ]
 [ 0.    0.    0.14 -0.45  0.  ]
 [ 1.   -0.71 -0.88 -0.07 -0.71]
 [ 0.    0.    0.14 -0.45 -0.  ]
 [ 0.    0.71  0.37  0.26  0.71]]


In [61]:
print(np.round(l3,2))

[ 1.  +0.j  -0.51+0.j  -0.14+0.3j -0.14-0.3j -0.  +0.j ]


In [62]:
print(np.round(P3,2))

[[ 0.36+0.j    0.74+0.j   -0.34-0.06j -0.34+0.06j -0.  +0.j  ]
 [ 0.26+0.j   -0.42+0.j   -0.12-0.11j -0.12+0.11j -0.8 +0.j  ]
 [ 0.71+0.j   -0.17+0.j    0.83+0.j    0.83-0.j    0.  +0.j  ]
 [ 0.26+0.j   -0.42+0.j   -0.12-0.11j -0.12+0.11j  0.53+0.j  ]
 [ 0.48+0.j    0.26+0.j   -0.24+0.28j -0.24-0.28j  0.27+0.j  ]]
