# AE 2 - Network 1

To save you some work, here is the matrix $M$ from the first exercise.

In [23]:
import numpy as np
M = np.array([[0,1/3,1,1/2,0],[1/3,0,0,0,0],[0,1/3,0,0,1],[1/3,0,0,0,0],[1/3,1/3,0,1/2,0]])

If you want to calculate an integer power of $M$ you can do it like this. Below we have calculated $M^2$:

In [2]:
np.linalg.matrix_power(M,2)

array([[0.27777778, 0.33333333, 0.        , 0.        , 1.        ],
       [0.        , 0.11111111, 0.33333333, 0.16666667, 0.        ],
       [0.44444444, 0.33333333, 0.        , 0.5       , 0.        ],
       [0.        , 0.11111111, 0.33333333, 0.16666667, 0.        ],
       [0.27777778, 0.11111111, 0.33333333, 0.16666667, 0.        ]])

If you want to experiment with some random surfers, you can start with some initial population, e.g.

In [3]:
p = np.array([[100],[100],[100],[100],[100]])

(Please feel free to try some other initial `p`).

Then you can calculate the recursive sequence $\mathbf{p}_j=M\mathbf{p}_{j-1}$, simply by repeatedly running the cell below, over and over, and observe how its output changes (and how it converges).

In [4]:
p = np.matmul(M,p)
print(p)

[[183.33333333]
 [ 33.33333333]
 [133.33333333]
 [ 33.33333333]
 [116.66666667]]


Alternatively (or both) you might alse want to calculate the eigenvectors of $M$ with eigenvalue 1. To get the eigenvalues and eigenvectors we can run

In [5]:
l,P = np.linalg.eig(M)
print("Eigenvalues = \n",np.round(l,2),"\n")
print("Corresponging basis vectors for eigenspace = \n",np.round(P,2))

Eigenvalues = 
 [ 1.  +0.j   -0.21+0.66j -0.21-0.66j -0.58+0.j   -0.  +0.j  ] 

Corresponging basis vectors for eigenspace = 
 [[ 0.69+0.j   -0.05-0.58j -0.05+0.58j  0.76+0.j   -0.  +0.j  ]
 [ 0.23+0.j   -0.26+0.11j -0.26-0.11j -0.44+0.j   -0.8 +0.j  ]
 [ 0.5 +0.j    0.61+0.j    0.61-0.j   -0.08+0.j   -0.  +0.j  ]
 [ 0.23+0.j   -0.26+0.11j -0.26-0.11j -0.44+0.j    0.53+0.j  ]
 [ 0.42+0.j   -0.04+0.37j -0.04-0.37j  0.19+0.j    0.27+0.j  ]]


The above tells us that the eigenspace associated with the eigenvalue 1 is:

$$\mathbf{x}\approx t(0.69,0.23,0.5,0.23,0.42),\quad t\in\mathbb{R}.$$

(we could multiply the given basis vector with -1, because anyway the eigenspace consists of all *multiples* of the same vector).

In [14]:
for i in range(10000):
   M = np.matmul(M, M)

In [26]:
M = np.matmul(M,M)
M

array([[0.3120237 , 0.32333105, 0.34979424, 0.29835391, 0.37328532],
       [0.11659808, 0.10834857, 0.12442844, 0.1213706 , 0.08230453],
       [0.23449169, 0.25474394, 0.20833333, 0.24151235, 0.28120713],
       [0.11659808, 0.10834857, 0.12442844, 0.1213706 , 0.08230453],
       [0.22028845, 0.20522786, 0.19301555, 0.21739255, 0.18089849]])