# AE 2 - Network 3

To save you some work, here is the matrix for Network 3, i.e.
$$M=\begin{bmatrix}
0 & 1/2 & 1/2 & 1/2 & 0 & 0\\
1/2 & 0 & 1/2 & 0 & 0 & 0\\
1/2 & 1/2 & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1/2 & 0 & 1\\
0 & 0 & 0 & 0 & 1 & 0
\end{bmatrix}.$$

In [261]:
import numpy as np
M = np.array([[0,0.5,0.5,0.5,0,0],[0.5,0,0.5,0,0,0],[0.5,0.5,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0.5,0,1],[0,0,0,0,1,0]])
print(M)

[[0.  0.5 0.5 0.5 0.  0. ]
 [0.5 0.  0.5 0.  0.  0. ]
 [0.5 0.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.5 0.  1. ]
 [0.  0.  0.  0.  1.  0. ]]


In [262]:
V = M * 0.85 + 1/40
V

array([[0.025, 0.45 , 0.45 , 0.45 , 0.025, 0.025],
       [0.45 , 0.025, 0.45 , 0.025, 0.025, 0.025],
       [0.45 , 0.45 , 0.025, 0.025, 0.025, 0.025],
       [0.025, 0.025, 0.025, 0.025, 0.025, 0.025],
       [0.025, 0.025, 0.025, 0.45 , 0.025, 0.875],
       [0.025, 0.025, 0.025, 0.025, 0.875, 0.025]])

As usual, you might want to experiment with some random surfers, such as

In [263]:
p = np.array([[100],[100],[100],[100],[100],[100]])

and see what happens when you repeat the formula:

In [284]:
for i in range(1000):
    p = np.matmul(V,p)
print(p)

[[117.14912281]
 [112.6754386 ]
 [112.6754386 ]
 [ 15.        ]
 [122.97297297]
 [119.52702703]]


And you might be interested in eigenvectors with eigenvalue 1.

In [285]:
l,P = np.linalg.eig(V)

In [286]:
print(np.round(l,2))

[ 1.    0.85  0.   -0.85 -0.43 -0.42]


In [287]:
print(np.round(P,2))

[[-0.45  0.37  0.35  0.    0.82  0.16]
 [-0.43  0.37 -0.35 -0.   -0.41 -0.77]
 [-0.43  0.37 -0.35  0.   -0.41  0.61]
 [-0.06  0.    0.71  0.    0.    0.  ]
 [-0.47 -0.55 -0.   -0.71  0.    0.  ]
 [-0.46 -0.55 -0.35  0.71 -0.    0.  ]]


For the second part of this exercise (involving the Google matrix), the following matrix might be useful:

In [7]:
V = 1/6*np.ones((6,6))
print(V)

[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]


The last calculations, you can do yourself:

In [27]:
M = np.matmul(M,M)
print(M)

[[0.33333333 0.33333333 0.33333333 0.16666667 0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.16666667 0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.16666667 0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         1.         0.        ]
 [0.         0.         0.         0.5        0.         1.        ]]


In [175]:
l, P= np.linalg.eig(M)

In [176]:
l

array([-0.5,  1. , -0.5,  1. , -1. ,  0. ])

In [178]:
print(np.round(P,2))

[[-0.82  0.58  0.23  0.    0.    0.35]
 [ 0.41  0.58 -0.79  0.    0.   -0.35]
 [ 0.41  0.58  0.57  0.    0.   -0.35]
 [ 0.    0.    0.    0.    0.    0.71]
 [ 0.    0.    0.    0.71  0.71  0.  ]
 [ 0.    0.    0.    0.71 -0.71 -0.35]]
